# 08. Callback

> 자바스크립트의 Callback에 대해 학습

[🏠Home](https://github.com/batboy118/Study_Note)

[◀Previous page ](./README.md)

---

<!-- TOC -->

- [1. 생성](#1-생성)
- [2. 접근](#2-접근)
- [3. 순회 방법 4가지](#3-순회-방법-4가지)
- [4. 추가](#4-추가)
- [5. 삭제](#5-삭제)
- [6. 검색](#6-검색)
- [7. 자주 사용되는 배열관련 API들](#7-자주-사용되는-배열관련-api들)

<!-- /TOC -->

## 1. callback

callback은 자바스크립트에서 비동기의 시작이다.

보통 자바스크립트는 동기언어이지만, callback을 쓰면 비동기적으로 동작하게 된다.

예를들어 아래 setTimeout으로 전달된 함수가 callback 함수이다.

```js
setTimeout(function () {
	console.log('2');
}, 1000);
```

callback함수도 두 가지로 나눌 수 있다.

- 동기 콜백

  ```js
  function printNow(print){
      print();
  }
  printNow(()=>console.log("Hello"));
  ```

- 비동기 콜백

  ```js
  function printNow(print){
      setTimeout(()=>console.log("Hello"), 1000);
  }
  printNow(()=>console.log("Hello"));
  ```

## 2. callback Hell

콜백 지옥의 예시를 살펴보자.

```js
class UserStorage {
    loginUser(id, password, onSuccess, onError){
        setTimeout(() => {
            if(
                (id === 'jason' && password === 'bear') ||
                (id === 'peter' && password === 'bat')
            ) {
                onSuccess(id);
            } else {
                onError(new Error('not found'));
            }
        }, 2000);
    }

    getRoles(user, onSuccess, onError){
        setTimeout(() => {
            if(user === 'jason') {
                onSuccess({name: 'jason', role: 'admin'});
            } else {
                onError(new Error('no access'));
            }
        },1000);
    }
}

const userStorage = new UserStorage();
const id = prompt ('endter your id');
const password = prompt ('endter your password');
userStorage.loginUser(
    id, 
    password, 
    (user) => { 
        userStorage.getRoles(
            user, 
            (uerWithRole) => {
                alert(`Hello ${uerWithRole.name}, you are ${uerWithRole.role}!`)
            },
            (error) => {console.log("Error")}
        )}, 
    (error) => {console.log("Error")}
)
```

- 위 코드는 id와 password를 입력하여 로그인하고, 역할을 받고, 유저를 확인하여 출력한다.

- 가독성이 좋지 않다.
- 디버깅하기 어렵다.
- 유지보수도 어렵다.

## 3. Promise

promise는 비동기를 간편하게 처리할 수 있도록 자바스크립트에서 제공해주는 Object이다.

Promise는 정해진 비동기 작업이 정상적으로 처리가 되었다면, 성고의 메세지와 함께 결과값을 전달해주고, 실패하면 에러를 던져준다.

비동기적인 것을 실행할 때 콜백함수 대신에 쓰인다.

promise를 사용하기 위해서는 상태(state), 제공자(producer), 소비자(consumer)에 대한 이해가 필요하다.

- state

  - pending : Promise가 만들어져서 지정된 작업이 실행되는 상태
  - fulfilled : 정해진 작업을 끝낸 상태
  - rejected : 문제가 발생한 상태

- producer : 프로미스를 만드는 것

  ```js
  const promise = new Promise((resolve, reject) => {
      console.log('doing Something');
      setTimeout(() => {
          resolve('jason');
      }, 2000);
  })
  //doing Something
  ```

  - promise는 resolve와 reject를 가지는 excutor(callback) 함수를 받는다.
  - 보통 비동기는 연산량이 많은 작업에 사용을 하게 된다.
  - **promise 인스턴스를 만드는 것만으로도, 콜백함수가 실행이 된다!**
    - doing Something이 출력된다.
    - 이것을 항상 염두해야 한다.(주의)
  - 위 예시에서는 2초 후에 resolve라는 함수에 jason 스트링을 인자로 주어 실행한다.

  ```js
  const promise = new Promise((resolve, reject) => {
      setTimeout(() => {
          reject(new Error('no network'));
      }, 2000);
  })
  ```

  - reject함수를 실행시킬 때는 보통 Error 객체를 생성해서 전달해주는데, 위 코드의 경우 2초 후에 에러를 발생시켜 프로그램을 죽인다.

- consumer : 프로미스를 사용하는 것

  - then, catch, finally 를 이용해서 값을 받아 올 수 있다.

  ```js
  const promise = new Promise((resolve, reject) => {
      setTimeout(() => {
          resolve('jason');
      }, 2000);
  })
  
  promise.then((value) => {
      console.log(value);  
  })
  //jason
  ```

  - then은 프로미스에서 resolve로 전달한 값을 파라미터로 받아서 실행시켜준다.

  ```js
  const promise = new Promise((resolve, reject) => {
      setTimeout(() => {
          reject(new Error('no network'));
      }, 2000);
  })
  
  promise
      .then((value) => {
      console.log(value);  
  })
      .catch(error => {
      console.log(error);
  });
  //error
  ```

  - 에러가 발생했을 때 프로그램을 멈추지 않고 특별한 처리를 하고 싶다면 `catch`를 사용하면 된다.
  - 위 코드는 콘솔에 error 객체를 출력할뿐 프로그램을 죽이지는 않는다.
  - 위 코드의 체이닝이 가능한 이유는, `then`은 **promise 객체**를 리턴하기 때문이다.

  최근에는 **finally**라는 메서드가 추가되었는데,  이 코드는 resolve나 reject에 관계 없이 무조건 실행되는 함수이다.

  ```js
  const promise = new Promise((resolve, reject) => {
      setTimeout(() => {
          reject(new Error('no network'));
      }, 2000);
  })
  
  promise
      .then((value) => {
      console.log(value);  
  })
      .catch(error => {
      console.log(error);
  })
      .finally(()=>{
      console.log("Always")
  });
  //error
  ```

## 4. Promise Chaining

```js
const fetchNumber = new Promise
```



